# Generated by Django 2.1.5 on 2019-01-11 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('host_id', models.AutoField(primary_key=True, serialize=False, verbose_name='服务器ID')),
                ('host_name', models.CharField(max_length=20, verbose_name='服务器名称')),
                ('host_ip', models.GenericIPAddressField(verbose_name='IP')),
            ],
        ),
        migrations.CreateModel(
            name='Service_Scripts',
            fields=[
                ('script_id', models.AutoField(primary_key=True, serialize=False, verbose_name='脚本ID')),
                ('script_name', models.CharField(max_length=50, verbose_name='脚本名称')),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('service_id', models.AutoField(primary_key=True, serialize=False, verbose_name='服务I')),
                ('service_name', models.CharField(max_length=20, verbose_name='服务器名称')),
                ('service_port', models.IntegerField(verbose_name='服务端口')),
                ('service_script', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='front_app.Service_Scripts', verbose_name='脚本')),
            ],
        ),
        migrations.AddField(
            model_name='host',
            name='host_services',
            field=models.ManyToManyField(to='front_app.Services', verbose_name='主机服务'),
        ),
    ]
